version: 1
formatters:
  simple:
    format: "%(message)s"
  more:
    format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: more
    level: DEBUG
    #filename: !!python/name:os.getcwd
    filename: log.txt
loggers:
  silentlogger:
    level: DEBUG
    handlers: [file]
  mapfa:
    level: DEBUG
    handlers: [console, file]
